PicoDrive source from RA-GCN by SuperrSonic

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,7 +39,7 @@ check_define()
 # "" means "autodetect".
 
 # TODO this is annoyingly messy. should have platform and device
-platform_list="generic pandora gph dingux retrofw opendingux[-gcw0] odbeta[-gcw0] miyoo rpi1 rpi2 ps2 psp win32"
+platform_list="generic pandora gp2x wiz caanoo dingux retrofw gcw0 rg350 opendingux miyoo rpi1 rpi2 psp"
 platform="generic"
 sound_driver_list="oss alsa sdl"
 sound_drivers=""
@@ -49,7 +49,8 @@ have_armv7=""
 have_arm_oabi=""
 have_arm_neon=""
 have_libavcodec=""
-have_gles=""
+have_libchdr=""
+have_gles="no"
 need_sdl="no"
 need_zlib="no"
 
@@ -58,14 +59,12 @@ CC="${CC-${CROSS_COMPILE}gcc}"
 CXX="${CXX-${CROSS_COMPILE}g++}"
 AS="${AS-${CROSS_COMPILE}as}"
 STRIP="${STRIP-${CROSS_COMPILE}strip}"
-LD="${LD-${CROSS_COMPILE}gcc}" # Use better gcc for linking
 SYSROOT=`$CC $CFLAGS $LDFLAGS --print-sysroot 2> /dev/null || true`
 config_mak="config.mak"
 
 fail()
 {
   echo "$@"
-  if test -n "$DUMP_CONFIG_LOG"; then cat config.log; fi
   exit 1
 }
 
@@ -73,16 +72,16 @@ fail()
 set_platform()
 {
   platform=$1
-  CFLAGS="$CFLAGS -D__`echo ${platform%-*} | tr '[a-z]' '[A-Z]'`__"
   case "$platform" in
   rpi1)
     MFLAGS="-mcpu=arm1176jzf-s -mfpu=vfp"
+    have_gles="yes"
     ;;
   rpi2)
     MFLAGS="-mcpu=cortex-a7 -mfpu=neon"
+    have_gles="yes"
     ;;
   generic)
-    MFLAGS=""
     ;;
   dingux)
     # dingoo a320, ritmix rzx-50, the like. all have Ingenic MIPS cpu <= JZ4755
@@ -90,6 +89,7 @@ set_platform()
     # use static linking since the lib situation is ... let's say vague
     #LDFLAGS="$LDFLAGS -static"
     # uses a pre-gcw0 version of opendingux
+    CFLAGS="$CFLAGS -D__DINGUX__"
     MFLAGS="-march=mips32 -msoft-float"
     platform="opendingux"
     ;;
@@ -97,39 +97,31 @@ set_platform()
     # devices using retrofw. AFAIK all have Ingenic MIPS JZ4760 with fpu
     sound_drivers="sdl"
     # uses it's own modified version of opendingux
+    CFLAGS="$CFLAGS -D__RETROFW__"
     MFLAGS="-march=mips32"
     platform="opendingux"
     ;;
-  opendingux | opendingux-gcw0)
+  opendingux | gcw0 | rg350)
     # more modern devices using opendingux, with Ingenic MIPS JZ4770 or newer
     sound_drivers="sdl"
-    # mostly based on opendingux for gcw0
-    CFLAGS="$CFLAGS -D__OPENDINGUX__"
-    [ "${platform#*gcw0}" = "" ] && CFLAGS="$CFLAGS -D__GCW0__"
+    # mostly based on opendingux for gcw0, save device type as C define.
+    CFLAGS="$CFLAGS -D__`echo $platform | tr '[a-z]' '[A-Z]'`__"
     MFLAGS="-march=mips32r2"
     platform="opendingux"
     ;;
   miyoo)
     # Miyoo BittBoy, PocketGO 1, PowKiddy V90/Q90 with Allwinner F1C100s
     sound_drivers="sdl"
-    CFLAGS="$CFLAGS -D__OPENDINGUX__"
+    CFLAGS="$CFLAGS -D__MIYOO__"
     MFLAGS="-mcpu=arm926ej-s -marm"
-    platform="opendingux"
-    ;;
-  odbeta | odbeta-gcw0)
-    # various devices with opendingux beta, arch flags from toolchain default
-    sound_drivers="sdl"
-    CFLAGS="$CFLAGS -D__OPENDINGUX__"
-    [ "${platform#*gcw0}" = "" ] && CFLAGS="$CFLAGS -D__GCW0__"
-    MFLAGS="" # toolchains are arch specific
-    platform="opendingux"
+    platform="miyoo"
     ;;
   pandora)
     sound_drivers="oss alsa"
     have_libavcodec="yes"
-    MFLAGS="-mcpu=cortex-a8 -mfpu=neon -mfloat-abi=softfp"
+    MFLAGS="-mcpu=cortex-a8 -mfpu=neon -mfloat-abi=hard"
     ;;
-  gph)
+  gp2x | wiz | caanoo)
     sound_drivers="oss"
     # compile for OABI if toolchain provides it (faster code on caanoo)
     have_arm_oabi="yes"
@@ -145,20 +137,9 @@ set_platform()
   psp)
     # use newlib
     SYSLIBS="-lc -lpspuser -lpspkernel"
+    CFLAGS="$CFLAGS -D__PSP__"
     MFLAGS="-march=allegrex"
     ARCH=mipsel
-    ;;
-  ps2)
-    # use newlib
-    SYSLIBS=""
-    MFLAGS=""
-    ARCH=mips64r5900el
-    ASFLAGS="$ASFLAGS -G0 -call_shared"
-    CFLAGS="$CFLAGS -D_EE -G0 -I${PS2SDK}/ee/include -I${PS2SDK}/common/include -I${PS2DEV}/gsKit/include -I${PS2SDK}/ports/include"
-    LDFLAGS="$LDFLAGS -Wl,-zmax-page-size=128 -T${PS2SDK}/ee/startup/linkfile -L${PS2SDK}/ee/lib -L${PS2DEV}/gsKit/lib -L${PS2SDK}/ports/lib"
-    ;;
-  win32)
-    MFLAGS=""
     ;;
   *)
     fail "unsupported platform: $platform"
@@ -179,8 +160,6 @@ for opt do
   ;;
   --with-sdl-gles=*) have_gles="$optarg"
   ;;
-  --with-zlib=*) need_zlib="$optarg"
-  ;;
   *) echo "ERROR: unknown option $opt"; show_help="yes"
   ;;
   esac
@@ -195,7 +174,6 @@ if [ "$show_help" = "yes" ]; then
   echo "                           available: $sound_driver_list"
   echo "  --with-libavcodec=yes|no use libavcodec for mp3 decoding"
   echo "  --with-sdl-gles=yes|no   enable GLES usage for SDL"
-  echo "  --with-zlib=yes|no       use internal zlib"
   echo "influential environment variables:"
   echo "  CROSS_COMPILE CC CXX AS STRIP CFLAGS ASFLAGS LDFLAGS LDLIBS"
   exit 1
@@ -214,8 +192,14 @@ if ! test -f "platform/libpicofe/README"; then
   fail "libpicofe is missing, please run 'git submodule update --init'"
 fi
 
+#if [ "$need_warm" = "yes" ]; then
+#  if ! test -f "frontend/warm/README"; then
+#    fail "wARM is missing, please run 'git submodule init && git submodule update'"
+#  fi
+#fi
+
 if [ -z "$ARCH" ]; then
-  ARCH=`$CC $MFLAGS $CFLAGS -dumpmachine | awk -F '-' '{print $1}'`
+  ARCH=`$CC -dumpmachine | awk -F '-' '{print $1}'`
 fi
 
 # CPU/ABI stuff first, else compile test may fail
@@ -280,7 +264,7 @@ arm*)
 esac
 
 case "$platform" in
-rpi1 | rpi2 | generic | opendingux | win32)
+rpi1 | rpi2 | generic | opendingux | miyoo)
   need_sdl="yes"
   ;;
 esac
@@ -350,40 +334,13 @@ EOF
   compile_object "$@"
 }
 
-check_gles()
+check_libchdr()
 {
-  # check for VideoCore stuff for Raspberry Pi
-  if [ VIDEOCORE != "no" -a -d /opt/vc/include -a -d /opt/vc/lib ]; then
-    CFLAGS="$CFLAGS -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux"
-    LDLIBS="$LDLIBS -L/opt/vc/lib"
-    if [ -f /opt/vc/lib/libbcm_host.so ]; then
-      LDLIBS="$LDLIBS -lbcm_host"
-    fi
-    VIDEOCORE="yes"
-  fi
-
-  # check for GLES headers
   cat > $TMPC <<EOF
-  #define EGL_NO_X11
-  #include <GLES/gl.h>
-  #include <EGL/egl.h>
-  int main(void) {
-    return (int)eglGetDisplay( (EGLNativeDisplayType)0 );
-  }
+  #include <libchdr/chd.h>
+  int main (int argc, char *argv[]) { chd_open("", 0, NULL, NULL); }
 EOF
-  if [ "$VIDEOCORE" = "yes" ] && compile_binary $CFLAGS $LDLIBS -lbrcmEGL -lbrcmGLESv2; then
-    have_gles="yes"
-#   LDLIBS="$LDLIBS -lbrcmEGL -lbrcmGLESv2" # non-standard names in old raspbian...
-  elif [ "$VIDEOCORE" = "yes" ] && compile_binary $CFLAGS $LDLIBS -lEGL -lGLESv2; then
-    have_gles="yes"
-#   LDLIBS="$LDLIBS -lEGL -lGLESv2" # on raspi GLESv1_CM is included in GLESv2
-  elif compile_binary $CFLAGS $LDLIBS -lEGL -lGLESv1_CM; then
-    have_gles="yes"
-#   LDLIBS="$LDLIBS -lEGL -lGLESv1_CM"
-  elif compile_binary $CFLAGS $LDLIBS -lEGL -lGLES_CM; then
-    have_gles="yes"
-#   LDLIBS="$LDLIBS -lEGL -lGLES_CM"
-  fi
+  compile_object "$@"
 }
 
 test -n "$SDL_CONFIG" || SDL_CONFIG="$(ls $SYSROOT/*bin*/sdl-config 2>/dev/null | grep /bin/sdl-config | head -n 1)"
@@ -391,9 +348,8 @@ test -n "$SDL_CONFIG" || SDL_CONFIG="$(ls $SYSROOT/*/*bin*/sdl-config 2>/dev/nul
 #test -n "$SDL_CONFIG" || SDL_CONFIG="$(ls $SYSROOT/*bin*/sdl2-config 2>/dev/null | grep /bin/sdl2-config | head -n 1)"
 #test -n "$SDL_CONFIG" || SDL_CONFIG="$(ls $SYSROOT/*/*bin*/sdl2-config 2>/dev/null | grep /bin/sdl2-config | head -n 1)"
 SDLVERSION=sdl && echo $SDL_CONFIG | grep -q sdl2 && SDLVERSION=sdl2
-test -n "$SDL_CONFIG" || SDL_CONFIG=false
 
-MAIN_LDLIBS="-lm"
+MAIN_LDLIBS="$LDLIBS -lm"
 
 check_zlib -lz && MAIN_LDLIBS="$MAIN_LDLIBS -lz" || need_zlib="yes"
 
@@ -410,6 +366,11 @@ y|Y|yes)
   fi ;;
 *) have_libavcodec="no" ;;
 esac
+
+#if check_libchdr; then
+#  have_libchdr="yes"
+#  MAIN_LDLIBS="-lchdr $MAIN_LDLIBS"
+#fi
 
 # find what audio support we can compile
 if [ "x$sound_drivers" = "x" ]; then
@@ -436,7 +397,7 @@ if [ "$need_sdl" = "yes" ]; then
   [ -x "$SDL_CONFIG" ] || \
     fail "sdl-config is missing; please install libsdl (libsdl1.2-dev)"
   CFLAGS="$CFLAGS `$SDL_CONFIG --cflags`"
-  LDLIBS="$LDLIBS `$SDL_CONFIG --libs`"
+  MAIN_LDLIBS="`$SDL_CONFIG --libs` $MAIN_LDLIBS"
   SYSLIBS="$SYSLIBS -ldl"
   need_dl=yes
   check_sdl `$SDL_CONFIG --libs` || fail "please install libsdl (libsdl1.2-dev)"
@@ -453,9 +414,6 @@ if [ "$need_dl" = "yes" ]; then
   esac
 fi
 
-# check for OpenGLES with SDL
-[ "$need_sdl" = "yes" -a "$have_gles" != "no" ] && check_gles
-
 if check_option -Wno-unused_result; then
   CFLAGS="$CFLAGS -Wno-unused-result"
 fi
@@ -464,17 +422,17 @@ fi
 test "x$have_armv6" != "x" || have_armv6="no"
 test "x$have_armv7" != "x" || have_armv7="no"
 test "x$have_libavcodec" != "x" || have_libavcodec="no"
-test "x$have_gles" != "x" || have_gles="no"
+test "x$have_libchdr" != "x" || have_libchdr="no"
 
 echo "architecture        $ARCH"
 echo "platform            $platform"
 echo "sound drivers       $sound_drivers"
 echo "C compiler          $CC"
 echo "C compiler flags    $MFLAGS $CFLAGS"
-echo "libraries           $LDLIBS $MAIN_LDLIBS"
+echo "libraries           $MAIN_LDLIBS"
 echo "linker flags        $LDFLAGS"
 echo "libavcodec (mp3)    $have_libavcodec"
-echo "use SDL with GLES   $have_gles"
+#echo "libchdr             $have_libchdr"
 # echo "ARMv7 optimizations $have_armv7"
 
 echo "# Automatically generated by configure" > $config_mak
@@ -486,11 +444,10 @@ echo "CC = $CC" >> $config_mak
 echo "CXX = $CXX" >> $config_mak
 echo "AS = $AS" >> $config_mak
 echo "STRIP = $STRIP" >> $config_mak
-echo "LD = $LD" >> $config_mak
 echo "CFLAGS += $MFLAGS $CFLAGS" >> $config_mak
 echo "ASFLAGS += $MFLAGS $ASFLAGS" >> $config_mak
 echo "LDFLAGS += $LDFLAGS" >> $config_mak
-echo "LDLIBS += $LDLIBS $MAIN_LDLIBS" >> $config_mak
+echo "LDLIBS += $MAIN_LDLIBS" >> $config_mak
 echo >> $config_mak
 
 echo "ARCH = $ARCH" >> $config_mak
@@ -501,6 +458,9 @@ if [ "$have_gles" = "yes" ]; then
 fi
 if [ "$have_libavcodec" = "yes" ]; then
   echo "HAVE_LIBAVCODEC = 1" >> $config_mak
+fi
+if [ "$have_libchdr" = "yes" ]; then
+  echo "HAVE_LIBCHDR = 1" >> $config_mak
 fi
 if [ "$need_zlib" = "yes" ]; then
   echo "PLATFORM_ZLIB = 1" >> $config_mak
